// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed Icon.png
var resourceIconPngData []byte
var resourceIconPng = &fyne.StaticResource{
	StaticName:    "Icon.png",
	StaticContent: resourceIconPngData,
}

//go:embed GameOverIcon.png
var resourceGameOverIconPngData []byte
var resourceGameOverIconPng = &fyne.StaticResource{
	StaticName:    "GameOverIcon.png",
	StaticContent: resourceGameOverIconPngData,
}

//go:embed PuzzleSolveIcon.png
var resourcePuzzleSolveIconPngData []byte
var resourcePuzzleSolveIconPng = &fyne.StaticResource{
	StaticName:    "PuzzleSolveIcon.png",
	StaticContent: resourcePuzzleSolveIconPngData,
}

//go:embed attribute.txt
var resourceAttributeTxtData []byte
var resourceAttributeTxt = &fyne.StaticResource{
	StaticName:    "attribute.txt",
	StaticContent: resourceAttributeTxtData,
}
